import Link from "next/link";

const paperSections = [
  {
    heading: "Abstract",
    paragraphs: [
      "Between 2018 and 2019, the United States imposed successive rounds of Section 301 tariffs on Chinese goods, and China retaliated with tariffs of its own. This paper examines how that escalation affected import costs, firm sourcing decisions, and the tone of bilateral trade relations. Drawing on the empirical trade literature, it argues that the tariffs were passed through almost entirely to U.S. importers and consumers, that firms responded less by reshoring production to the United States than by diversifying suppliers across third countries, and that the uncertainty generated by an unpredictable tariff schedule shaped business planning as much as the tariffs themselves. The paper closes by distinguishing short-run price and volume effects from the longer-run structural realignment of supply chains, and it flags specific places where Census, USTR, and price-index data should be inserted once gathered.",
    ],
  },
  {
    heading: "Introduction",
    paragraphs: [
      "In March 2018, the Office of the U.S. Trade Representative concluded a Section 301 investigation finding that Chinese practices around technology transfer and intellectual property justified new tariffs. Over the following eighteen months, the United States implemented several tariff lists covering hundreds of billions of dollars in Chinese goods, while China imposed retaliatory tariffs on U.S. exports. The exact average effective tariff rate depends on product coverage, exclusions, and the calculation method; this paper does not report a single aggregate rate without a reproducible tariff dataset.",
      "This paper asks a narrower question than \"did the trade war work.\" It asks how tariff escalation moved through the economy: who absorbed the higher costs, how quickly and in what direction firms adjusted their sourcing, and what the pattern of retaliation did to the broader relationship between the two governments. The thesis is that cost pass-through was rapid and largely borne by U.S. buyers, that the sourcing response was real but partial and geographically dispersed rather than a return of production to U.S. soil, and that the uncertainty inherent in an unpredictable tariff calendar mattered for firm behavior independently of the tariffs' final level.",
    ],
  },
  {
    heading: "Background",
    paragraphs: [
      "The legal vehicle for the 2018-2019 tariffs was Section 301 of the Trade Act of 1974. USTR's chronology records an initial $34 billion tranche effective July 6, 2018; a second $16 billion tranche effective August 23, 2018; a $200 billion tranche initially at 10 percent from September 24, 2018 and increased to 25 percent on May 10, 2019; and a later List 4 action that was split, with List 4A taking effect at 15 percent on September 1, 2019 and List 4B suspended before taking effect. Rates and exclusions changed later, so the action list should not be summarized as one uniform $300 billion tariff. USTR's Section 301 action record and contemporaneous releases are linked above.",
      "China's retaliation followed a similar escalatory logic but with a distinct sectoral emphasis. Tariffs on U.S. soybeans, pork, and other agricultural exports were used deliberately, targeting politically salient U.S. export categories rather than mirroring the U.S. tariff lists product for product [Add USTR/Census bilateral retaliation data here]. The result by the end of 2019 was a tariff regime covering the large majority of two-way trade between the world's two largest economies, an outcome without precedent in the postwar trading system in terms of the dollar value affected.",
    ],
  },
  {
    heading: "Cost Pass-Through and Domestic Prices",
    paragraphs: [
      "The clearest empirical finding from the 2018-2019 episode concerns tariff incidence at the border. Amiti, Redding, and Weinstein (2019), in the Journal of Economic Perspectives, found complete pass-through into U.S. prices of imported goods; that is not evidence that every retail price rose by the tariff amount. They estimated a U.S. real-income reduction of $1.4 billion per month by the end of 2018. Fajgelbaum, Goldberg, Kennedy, and Khandelwal (2020), in the Quarterly Journal of Economics, estimated $51 billion in gross losses to consumers and firms (0.27 percent of GDP) before accounting for tariff revenue and gains to protected producers; their estimated net aggregate real-income loss was $7.2 billion (0.04 percent of GDP). These are model-based estimates with distinct gross and net concepts.",
      "These two figures are not contradictory. The larger number captures the gross cost borne by importers and downstream consumers; the smaller number captures the net welfare effect once tariff revenue and producer surplus are credited back to the U.S. side of the ledger. Read together, they support a specific claim: the tariffs functioned less like a tax that vanished into thin air and more like a transfer, moving money from U.S. import-consuming firms and households toward the U.S. Treasury and toward protected domestic producers, with a smaller net efficiency loss layered on top. This matters for how the paper's later sections interpret firm behavior, because a firm facing a 25 percent cost increase on an imported input does not know, in real time, whether that cost is temporary, negotiable, or the new baseline. [Add BLS import price index (MXPICHN or similar series) and CPI category data to show the timing of price pass-through here.]",
    ],
  },
  {
    heading: "Trade Volumes and the Limits of Reshoring",
    paragraphs: [
      "Fajgelbaum et al. (2020) estimated that imports in targeted product-country groups fell 31.5 percent and targeted U.S. exports fell 11.0 percent; these are estimates for the study's tariff-exposed products, not percentage changes in all U.S.-China trade. The U.S. Department of Agriculture did provide Market Facilitation Program payments to eligible producers affected by retaliatory tariffs. These facts do not by themselves establish that Chinese exporters had more alternative buyers or that U.S. exporters had fewer; those firm/market-access claims need separate evidence.",
      "The more interesting question for a paper on firm behavior is where the displaced trade went. The tariffs targeted China specifically, not imports in general, so a rational importer facing a 25 percent cost increase on Chinese goods had an incentive to shift sourcing to countries not subject to the tariff, not necessarily to shift production back to the United States. The available evidence on this point, once assembled, should distinguish between genuine relocation of manufacturing capacity and a more superficial rerouting of trade flows, sometimes called transshipment, in which final assembly moves to a third country while Chinese-made components and subassemblies remain embedded in the product. [Add Census bilateral trade data for Vietnam, Mexico, and Taiwan imports 2017-2020 here, alongside any available input-output evidence on Chinese value-added content in those imports.] If the data show U.S. imports from China falling while U.S. imports from Vietnam rise by a comparable amount, and Vietnam's own imports of intermediate goods from China rise at the same time, that pattern would support the view that the tariffs shifted the geography of trade more than they reduced U.S. dependence on Chinese-linked supply chains.",
    ],
  },
  {
    heading: "Uncertainty and Firm Planning",
    paragraphs: [
      "A tariff that is announced, delayed, escalated, and partially reversed within an eighteen-month window creates a distinct kind of cost separate from the tariff rate itself: the cost of not knowing what the rate will be next quarter. Handley and Limao's earlier work on trade policy uncertainty, developed around China's 2001 WTO accession, showed that the removal of tariff uncertainty (through a binding commitment) had measurable effects on trade and prices independent of any change in the applied tariff rate. The 2018-2019 episode ran the same logic in reverse: the reintroduction of uncertainty, through an unpredictable sequence of tariff lists, deadlines, and negotiating rounds, plausibly affected firm investment and inventory decisions even before any particular tariff took effect.",
      "Trade-policy uncertainty provides a plausible channel for firms to delay or alter investment, but this draft has not assembled firm-level or regional survey evidence showing that shipment frontloading, inventory buffers, and delayed capital spending were widespread in 2018-2019. Caldara et al. (2020) study the economic effects of trade-policy uncertainty, including investment responses; applying that result to specific behaviors by U.S. firms in this episode requires direct evidence. The optionality mechanism is therefore a hypothesis here, not an observed project finding.",
    ],
  },
  {
    heading: "Bilateral Relations and the WTO Context",
    paragraphs: [
      "China challenged the U.S. Section 301 measures at the WTO in dispute DS543. The broad claim that both countries filed reciprocal WTO complaints over this episode is not established in this draft and is omitted. The USTR records the Phase One agreement's signature on January 15, 2020; the agreement did not remove the existing tariff actions, so the tariff regime continued after the agreement. The policy record and the WTO dispute record should be read separately.",
    ],
  },
  {
    heading: "Limitations and Counterarguments",
    paragraphs: [
      "Two qualifications deserve space. First, the general equilibrium estimates cited above rest on modeling assumptions, particularly about elasticities of substitution and the speed of firm adjustment, and different papers using different assumptions arrive at real income effects that vary by an order of magnitude between the gross and net measures discussed above. A reader should treat the dollar figures as informative about direction and rough magnitude rather than as precise, uncontested numbers. Second, proponents of the tariff strategy have argued that the short-run costs documented in this paper were the price of a longer-run negotiating objective, and that the Phase One agreement, along with subsequent policy shifts on export controls and industrial policy, should be evaluated as a multi-year strategy rather than judged solely on 2018-2019 price and volume data. This paper does not attempt to adjudicate that broader strategic question; it focuses on the narrower, better-measured channels of cost pass-through, sourcing adjustment, and uncertainty, and leaves the longer-run strategic assessment to research that extends past the 2019 window.",
    ],
  },
  {
    heading: "Conclusion",
    paragraphs: [
      "The 2018-2019 tariff escalation was a major policy shock, but not a randomized natural experiment. Published studies find substantial pass-through to U.S. import prices, while precise retail-price effects and welfare estimates depend on the measure and model. Federal Reserve research documents trade diversion to third countries, but this alone does not demonstrate widespread reshoring or quantify Chinese value added in diverted flows. The uncertainty channel is plausible and studied in the literature, but the firm behaviors described here remain unverified without direct survey or firm-level evidence. These limits counsel against treating this draft's descriptive account as a causal estimate of tariff effectiveness.",
    ],
  },
];

const bibliographyGuidance = [
  "Peer-reviewed and NBER/working-paper evidence: Amiti, Redding & Weinstein (2019, Journal of Economic Perspectives); Fajgelbaum, Goldberg, Kennedy & Khandelwal (2020, Quarterly Journal of Economics); Handley & Limao on trade policy uncertainty; Caldara, Iacoviello, Molligo, Prestipino & Raffo (2020) on the trade policy uncertainty index.",
  "Government data: U.S. Census Bureau bilateral trade data by HS code (China, Vietnam, Mexico, Taiwan); BLS import/export price indexes; FRED series for real income, GDP, and investment; USDA Market Facilitation Program payment data.",
  "Policy documents: USTR Section 301 investigation report and subsequent Federal Register tariff action notices; WTO dispute settlement case filings (DS543 and related).",
  "Regional Fed surveys: Dallas Fed and Richmond Fed manufacturing survey data on sourcing and capex plans, 2018-2019.",
  "Reputable press for context and timeline verification only, not as primary evidence: Reuters, WSJ, FT trade-war timelines.",
];

const suggestedFigures = [
  "Timeline chart of tariff list effective dates and rates (U.S. on China; China on U.S.), 2018-2019.",
  "Line chart: U.S. average effective tariff rate on Chinese imports vs. China's average effective tariff rate on U.S. exports, monthly, 2017-2020.",
  "Line chart: U.S. imports from China vs. U.S. imports from Vietnam, Mexico, and Taiwan, indexed to a 2017 base, to show sourcing substitution.",
  "Bar or line chart: BLS import price index for tariffed product categories vs. non-tariffed categories, to illustrate pass-through.",
  "Line chart: a trade policy uncertainty index overlaid with private nonresidential fixed investment, to show the timing relationship.",
  "Table: summary of key empirical estimates (Amiti-Redding-Weinstein vs. Fajgelbaum et al.), showing gross cost, net welfare loss, and import volume decline side by side.",
];

const evidenceNeeds = [
  "USTR/Federal Register: exact effective dates and rates for each Section 301 tariff list, and any subsequent modifications or exclusions granted.",
  "Census Bureau: bilateral trade values by HS code for China, Vietnam, Mexico, and Taiwan, 2017-2020, to support the sourcing-shift argument.",
  "BLS: import price index series broken out by tariffed vs. non-tariffed product categories, to date the timing of price pass-through against tariff effective dates.",
  "USDA: Market Facilitation Program payment totals, to quantify the fiscal offset to agricultural retaliation losses.",
  "WTO: case numbers, filing dates, and status for the relevant U.S.-China disputes filed during this period.",
  "Regional Federal Reserve surveys: specific survey questions and response data on firm sourcing and capex plans during 2018-2019.",
  "A trade policy uncertainty index dataset (Caldara et al. or equivalent), for the uncertainty-investment chart.",
];

export default function TradeWarShockPaperPage() {
  return (
    <main className="min-h-screen bg-[#070a0d] text-white">
      <section className="mx-auto max-w-5xl px-6 py-16">
        <p className="text-[11px] uppercase tracking-[0.38em] text-[var(--accent-soft)]">
          Full Paper // Case File 01
        </p>
        <h1 className="mt-6 font-[family:var(--font-display)] text-4xl leading-tight text-white sm:text-6xl">
          Tariff Escalation and Firm Behavior: Import Costs, Sourcing Shifts, and the
          Breakdown of U.S.-China Trade Relations, 2018-2019
        </h1>

        <aside className="mt-6 rounded-xl border border-amber-200/20 bg-amber-100/[0.04] px-5 py-4 text-sm leading-6 text-white/70" role="note">
          Working research draft. Bracketed notes mark evidence or citations still to be added; statements attached to those notes should not be treated as fully verified. Verified references include USTR's <a className="underline" href="https://ustr.gov/issue-areas/enforcement/section-301-investigations/section-301-china/200-billion-trade-action" target="_blank" rel="noreferrer">Section 301 action chronology</a>, <a className="underline" href="https://www.aeaweb.org/articles?id=10.1257/jep.33.4.187" target="_blank" rel="noreferrer">Amiti, Redding &amp; Weinstein (2019)</a>, <a className="underline" href="https://www.nber.org/papers/w25638" target="_blank" rel="noreferrer">Fajgelbaum et al. (2020)</a>, and <a className="underline" href="https://www.federalreserve.gov/econres/notes/feds-notes/global-trade-patterns-in-the-wake-of-the-2018-2019-u-s-china-tariff-hikes-20240412.html" target="_blank" rel="noreferrer">Federal Reserve research on trade diversion</a>.
        </aside>

        <div className="mt-10 rounded-[2rem] border border-white/10 bg-white/[0.04] p-8 sm:p-10">
          {paperSections.map((section) => (
            <article key={section.heading} className="mb-10 last:mb-0">
              <h2 className="font-[family:var(--font-display)] text-3xl text-white sm:text-4xl">
                {section.heading}
              </h2>
              <div className="mt-5 space-y-5 text-[1.03rem] leading-8 text-white/72">
                {section.paragraphs.map((paragraph, index) => (
                  <p key={`${section.heading}-${index}`}>{paragraph}</p>
                ))}
              </div>
            </article>
          ))}
        </div>

        <section className="mt-10 grid gap-6 lg:grid-cols-3">
          <article className="rounded-[1.8rem] border border-white/10 bg-white/[0.04] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Bibliography Guidance
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/64">
              {bibliographyGuidance.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>

          <article className="rounded-[1.8rem] border border-white/10 bg-white/[0.04] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Suggested Charts and Tables
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/64">
              {suggestedFigures.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>

          <article className="rounded-[1.8rem] border border-white/10 bg-[linear-gradient(135deg,rgba(255,184,77,0.1),rgba(255,255,255,0.03))] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Evidence Still Needed
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/70">
              {evidenceNeeds.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>
        </section>

        <div className="mt-12">
          <Link
            href="/trade-war-shock"
            className="inline-flex min-h-[56px] items-center justify-center rounded-[999px] border border-[var(--line-strong)] px-6 text-[11px] font-extrabold uppercase tracking-[0.26em] text-white transition hover:border-[var(--accent)] hover:bg-[var(--accent)] hover:text-[var(--bg)]"
          >
            Back to Case File
          </Link>
        </div>
      </section>
    </main>
  );
}
