import Link from "next/link";

const paperSections = [
  {
    heading: "Abstract",
    paragraphs: [
      "Between 2018 and 2019, the United States imposed successive rounds of Section 301 tariffs on Chinese goods, and China retaliated with tariffs of its own. This paper examines how that escalation affected import costs, firm sourcing decisions, and the tone of bilateral trade relations. Drawing on the empirical trade literature, it argues that the tariffs were passed through almost entirely to U.S. importers and consumers, that firms responded less by reshoring production to the United States than by diversifying suppliers across third countries, and that the uncertainty generated by an unpredictable tariff schedule shaped business planning as much as the tariffs themselves. The paper closes by distinguishing short-run price and volume effects from the longer-run structural realignment of supply chains, and it flags specific places where Census, USTR, and price-index data should be inserted once gathered.",
    ],
  },
  {
    heading: "Introduction",
    paragraphs: [
      "In March 2018, the Office of the U.S. Trade Representative concluded a Section 301 investigation finding that Chinese practices around technology transfer and intellectual property justified new tariffs. Over the following eighteen months, the United States implemented several tariff lists covering hundreds of billions of dollars in Chinese goods, while China imposed retaliatory tariffs on U.S. exports. The exact average effective tariff rate depends on product coverage, exclusions, and the calculation method; this paper does not report a single aggregate rate without a reproducible tariff dataset.",
      "This paper asks a narrower question than \"did the trade war work.\" It asks how tariff escalation moved through the economy: who absorbed the higher costs, how quickly and in what direction firms adjusted their sourcing, and what the pattern of retaliation did to the broader relationship between the two governments. The thesis is that cost pass-through was rapid and largely borne by U.S. buyers, that the sourcing response was real but partial and geographically dispersed rather than a return of production to U.S. soil, and that the uncertainty inherent in an unpredictable tariff calendar mattered for firm behavior independently of the tariffs' final level.",
    ],
  },
  {
    heading: "Background",
    paragraphs: [
      "The legal vehicle for the 2018-2019 tariffs was Section 301 of the Trade Act of 1974. USTR's chronology records an initial $34 billion tranche effective July 6, 2018; a second $16 billion tranche effective August 23, 2018; a $200 billion tranche initially at 10 percent from September 24, 2018 and increased to 25 percent on May 10, 2019; and a later List 4 action that was split, with List 4A taking effect at 15 percent on September 1, 2019 and List 4B suspended before taking effect. Rates and exclusions changed later, so the action list should not be summarized as one uniform $300 billion tariff. USTR's Section 301 action record and contemporaneous releases are linked above.",
      "China imposed retaliatory tariffs on U.S. exports in successive rounds. USDA's 2018 Market Facilitation Program records eligible commodities including soybeans, pork, and other farm products and describes the aid as a response to foreign retaliatory tariffs. This establishes agricultural exposure and government assistance, not that each tariff was selected for a specific political purpose. Exact product coverage and value should be verified against the relevant tariff schedules before quantifying the effect.",
    ],
  },
  {
    heading: "Cost Pass-Through and Domestic Prices",
    paragraphs: [
      "The clearest empirical finding from the 2018-2019 episode concerns tariff incidence at the border. Amiti, Redding, and Weinstein (2019), in the Journal of Economic Perspectives, found complete pass-through into U.S. prices of imported goods; that is not evidence that every retail price rose by the tariff amount. They estimated a U.S. real-income reduction of $1.4 billion per month by the end of 2018. Fajgelbaum, Goldberg, Kennedy, and Khandelwal (2020), in the Quarterly Journal of Economics, estimated $51 billion in gross losses to consumers and firms (0.27 percent of GDP) before accounting for tariff revenue and gains to protected producers; their estimated net aggregate real-income loss was $7.2 billion (0.04 percent of GDP). These are model-based estimates with distinct gross and net concepts.",
      "These two figures are not contradictory. The larger number captures the gross cost borne by importers and downstream consumers; the smaller number captures the net welfare effect once tariff revenue and producer surplus are credited back to the U.S. side of the ledger. Read together, they support a specific claim: the tariffs functioned less like a tax that vanished into thin air and more like a transfer, moving money from U.S. import-consuming firms and households toward the U.S. Treasury and toward protected domestic producers, with a smaller net efficiency loss layered on top. This matters for how the paper's later sections interpret firm behavior, because a firm facing a 25 percent cost increase on an imported input does not know, in real time, whether that cost is temporary, negotiable, or the new baseline. [Add BLS import price index (MXPICHN or similar series) and CPI category data to show the timing of price pass-through here.]",
    ],
  },
  {
    heading: "Trade Volumes and the Limits of Reshoring",
    paragraphs: [
      "Fajgelbaum et al. (2020) estimated that imports in targeted product-country groups fell 31.5 percent and targeted U.S. exports fell 11.0 percent; these are estimates for the study's tariff-exposed products, not percentage changes in all U.S.-China trade. The U.S. Department of Agriculture did provide Market Facilitation Program payments to eligible producers affected by retaliatory tariffs. These facts do not by themselves establish that Chinese exporters had more alternative buyers or that U.S. exporters had fewer; those firm/market-access claims need separate evidence.",
      "Importers facing additional duties had an incentive to consider suppliers outside the tariff lists, but this mechanism alone does not show how much firms actually shifted sourcing or whether production returned to the United States. Federal Reserve research documents changes in U.S. sourcing geography and increased China import shares among some U.S. supplier countries. It also finds that the scope for rerouting Chinese goods through third countries appeared limited through 2022. Such trade-flow patterns do not establish illegal transshipment, and the value-added evidence used in the Federal Reserve analysis does not extend beyond 2020. Product-level Census data, firm ownership/investment data, and input-output measures answer different questions and should not be treated as interchangeable.",
    ],
  },
  {
    heading: "Uncertainty and Firm Planning",
    paragraphs: [
      "A changing tariff schedule can create uncertainty distinct from the tariff rate ultimately paid. Handley and Limão's work on China's WTO accession studies the effects of reducing trade-policy uncertainty in a different setting; it motivates a mechanism but does not directly establish the 2018-2019 U.S. firm response. Caldara et al. (2019) construct trade-policy uncertainty measures and report investment effects using firm-level and aggregate evidence. Applying those results to specific front-loading or sourcing behaviors during this tariff episode requires direct data.",
      "Trade-policy uncertainty provides a plausible channel for firms to delay or alter investment, but this draft has not assembled firm-level or regional survey evidence showing that shipment frontloading, inventory buffers, and delayed capital spending were widespread in 2018-2019. Caldara et al. (2019) study the economic effects of trade-policy uncertainty, including investment responses; applying that result to specific behaviors by U.S. firms in this episode requires direct evidence. The optionality mechanism is therefore a hypothesis here, not an observed project finding.",
    ],
  },
  {
    heading: "Bilateral Relations and the WTO Context",
    paragraphs: [
      "China requested consultations over U.S. Section 301 measures in WTO disputes DS543 (April 4, 2018) and DS565 (August 23, 2018). The United States separately requested consultations in DS558 (July 16, 2018) concerning Chinese additional duties following U.S. steel and aluminum measures under Section 232; it should not be described as a direct reciprocal WTO case about Section 301. The USTR records the Phase One agreement's signature on January 15, 2020; the existing Section 301 actions continued afterward. The policy and dispute records should be read separately.",
    ],
  },
  {
    heading: "Limitations and Counterarguments",
    paragraphs: [
      "Two qualifications deserve space. First, the general equilibrium estimates cited above rest on modeling assumptions, particularly about elasticities of substitution and the speed of firm adjustment, and different papers using different assumptions arrive at real income effects that vary by an order of magnitude between the gross and net measures discussed above. A reader should treat the dollar figures as informative about direction and rough magnitude rather than as precise, uncontested numbers. Second, proponents of the tariff strategy have argued that the short-run costs documented in this paper were the price of a longer-run negotiating objective, and that the Phase One agreement, along with subsequent policy shifts on export controls and industrial policy, should be evaluated as a multi-year strategy rather than judged solely on 2018-2019 price and volume data. This paper does not attempt to adjudicate that broader strategic question; it focuses on the narrower, better-measured channels of cost pass-through, sourcing adjustment, and uncertainty, and leaves the longer-run strategic assessment to research that extends past the 2019 window.",
    ],
  },
  {
    heading: "Conclusion",
    paragraphs: [
      "The 2018-2019 tariff escalation was a major policy shock, but not a randomized natural experiment. Published studies find substantial pass-through to U.S. import prices, while precise retail-price effects and welfare estimates depend on the measure and model. Federal Reserve research documents trade diversion to third countries, but this alone does not demonstrate widespread reshoring or quantify Chinese value added in diverted flows. The uncertainty channel is plausible and studied in the literature, but the firm behaviors described here remain unverified without direct survey or firm-level evidence. These limits counsel against treating this draft's descriptive account as a causal estimate of tariff effectiveness.",
    ],
  },
];

const bibliographyGuidance = [
  "Peer-reviewed and working-paper evidence: Amiti, Redding & Weinstein (2019, Journal of Economic Perspectives); Fajgelbaum, Goldberg, Kennedy & Khandelwal (2020, Quarterly Journal of Economics); Caldara et al. (2019, Federal Reserve IFDP 1256, preliminary working paper) on trade-policy uncertainty. These studies do not verify every firm behavior discussed in this draft.",
  "Government data: U.S. Census Bureau bilateral trade data by HS code (China, Vietnam, Mexico, Taiwan); BLS import/export price indexes; FRED series for real income, GDP, and investment; USDA Market Facilitation Program payment data.",
  "Policy documents: USTR Section 301 action notices; WTO disputes DS543, DS565, and DS558 (distinct measures); USDA's 2018 Market Facilitation Program record.",
  "Regional Fed surveys: Dallas Fed and Richmond Fed manufacturing survey data on sourcing and capex plans, 2018-2019.",
  "Reputable press for context and timeline verification only, not as primary evidence: Reuters, WSJ, FT trade-war timelines.",
];

const suggestedFigures = [
  "Timeline chart of tariff list effective dates and rates (U.S. on China; China on U.S.), 2018-2019.",
  "Line chart: U.S. average effective tariff rate on Chinese imports vs. China's average effective tariff rate on U.S. exports, monthly, 2017-2020.",
  "Line chart: U.S. imports from China vs. U.S. imports from Vietnam, Mexico, and Taiwan, indexed to a 2017 base, to show sourcing substitution.",
  "Bar or line chart: BLS import price index for tariffed product categories vs. non-tariffed categories, to illustrate pass-through.",
  "Line chart: a trade policy uncertainty index overlaid with private nonresidential fixed investment, to show the timing relationship.",
  "Table: summary of key empirical estimates (Amiti-Redding-Weinstein vs. Fajgelbaum et al.), showing gross cost, net welfare loss, and import volume decline side by side.",
];

const evidenceNeeds = [
  "Census Bureau: bilateral trade values by HS code for China, Vietnam, Mexico, and Taiwan, 2017-2020, to support the sourcing-shift argument.",
  "BLS: import price index series broken out by tariffed vs. non-tariffed product categories, to date the timing of price pass-through against tariff effective dates.",
  "USDA: Market Facilitation Program payment totals, to quantify the fiscal offset to agricultural retaliation losses.",
  "Regional Federal Reserve surveys: specific survey questions and response data on firm sourcing and capex plans during 2018-2019.",
  "A trade policy uncertainty index dataset (Caldara et al. or equivalent), for the uncertainty-investment chart.",
];

const verifiedReferences = [
  { label: "USTR (2018-2019), Section 301 tariff actions and product schedules", note: "Primary policy record for product coverage, effective dates, rates, postponements, and exclusions; the draft no longer asserts one aggregate average tariff rate.", href: "https://ustr.gov/issue-areas/enforcement/section-301-investigations/tariff-actions" },
  { label: "Amiti, Redding & Weinstein (2019), Journal of Economic Perspectives 33(4), 187-210", note: "Finds pass-through into domestic prices of imported goods and estimates real-income effects; not a claim that every consumer retail price rose by the tariff amount.", href: "https://www.aeaweb.org/articles?id=10.1257/jep.33.4.187" },
  { label: "Fajgelbaum et al. (2020), Quarterly Journal of Economics 135(1), 1-55", note: "Study-specific estimates of tariff-exposed imports, exports, prices, and modeled welfare; not population-wide bilateral trade percentage changes.", href: "https://academic.oup.com/qje/article/135/1/1/5626442" },
  { label: "USTR (2018), statement on Section 301 and retaliation", note: "Contemporaneous record of U.S. and Chinese tariff actions; USDA's 2018 MFP fact sheet separately lists eligible agricultural commodities but does not establish political targeting intent.", href: "https://ustr.gov/about-us/policy-offices/press-office/press-releases/2018/july/statement-us-trade-representative" },
  { label: "USDA Farm Service Agency (2018), Market Facilitation Program fact sheet", note: "Documents assistance to eligible agricultural producers affected by foreign retaliatory tariffs; it is not a causal estimate of producer losses.", href: "https://www.fsa.usda.gov/sites/default/files/documents/Market_Facilitation_Program_Fact_Sheet_September_2018B.pdf" },
  { label: "Hoang & Lewis (2024), Federal Reserve FEDS Notes", note: "Finds limited evidence of rerouting through third countries through 2022; discusses indirect reliance and data limits, not shipment-level proof of illegal transshipment.", href: "https://www.federalreserve.gov/econres/notes/feds-notes/as-the-u-s-is-derisking-from-china-Other-foreign-u-s-suppliers-are-relying-more-on-chinese-imports-20240802.html" },
  { label: "Caldara et al. (2019), Federal Reserve IFDP 1256", note: "Preliminary working paper measuring trade-policy uncertainty and investment responses; it does not verify specific 2018-2019 shipment-frontloading claims.", href: "https://www.federalreserve.gov/econres/ifdp/files/ifdp1256.pdf" },
  { label: "Handley & Limão (2017), Policy Uncertainty, Trade, and Welfare, American Economic Review 107(9), 2731-2783", note: "Studies uncertainty around China's WTO accession, not the 2018-2019 U.S. firm response.", href: "https://www.aeaweb.org/articles?id=10.1257/aer.20141419" },
  { label: "WTO DS543: United States — Tariff Measures on Certain Goods from China", note: "China's April 2018 complaint challenging U.S. Section 301 tariff measures.", href: "https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds543_e.htm" },
  { label: "WTO, DS565: United States — Tariff Measures on Certain Goods from China II", note: "China's August 2018 complaint concerning additional U.S. tariff measures.", href: "https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds565_e.htm" },
  { label: "WTO, DS558: China — Additional Duties on Certain Products from the United States", note: "U.S. complaint about separate Chinese additional duties following U.S. Section 232 measures; not a reciprocal Section 301 case.", href: "https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds558_e.htm" },
  { label: "USTR (2020), Economic and Trade Agreement Between the United States and China (Phase One)", note: "Official agreement and date record; the tariff schedules should be checked separately for actions that remained in force.", href: "https://ustr.gov/phase-one" },
];

export default function TradeWarShockPaperPage() {
  return (
    <main className="min-h-screen bg-[#070a0d] text-white">
      <section className="mx-auto max-w-5xl px-6 py-16">
        <p className="text-[11px] uppercase tracking-[0.38em] text-[var(--accent-soft)]">
          Full Paper // Case File 01
        </p>
        <h1 className="mt-6 font-[family:var(--font-display)] text-4xl leading-tight text-white sm:text-6xl">
          Tariff Escalation and Firm Behavior: Import Costs, Sourcing Shifts, and the
          Breakdown of U.S.-China Trade Relations, 2018-2019
        </h1>

        <aside className="mt-6 rounded-xl border border-amber-200/20 bg-amber-100/[0.04] px-5 py-4 text-sm leading-6 text-white/70" role="note">
          Working research draft. Bracketed notes mark evidence or citations still to be added; claims tied to unresolved notes should not be treated as fully verified. The linked source shelf below summarizes what the verified sources do and do not establish.
        </aside>

        <section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.03] p-6" aria-labelledby="verified-sources-title">
          <h2 id="verified-sources-title" className="text-xs font-bold uppercase tracking-[0.22em] text-[var(--accent-soft)]">Verified sources and scope</h2>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            {verifiedReferences.map((source) => (
              <article key={source.href} className="rounded-xl border border-white/10 p-4">
                <a className="text-sm font-semibold text-white underline decoration-white/30 underline-offset-4" href={source.href} target="_blank" rel="noreferrer">{source.label}</a>
                <p className="mt-2 text-sm leading-6 text-white/60">{source.note}</p>
              </article>
            ))}
          </div>
        </section>

        <div className="mt-10 rounded-[2rem] border border-white/10 bg-white/[0.04] p-8 sm:p-10">
          {paperSections.map((section) => (
            <article key={section.heading} className="mb-10 last:mb-0">
              <h2 className="font-[family:var(--font-display)] text-3xl text-white sm:text-4xl">
                {section.heading}
              </h2>
              <div className="mt-5 space-y-5 text-[1.03rem] leading-8 text-white/72">
                {section.paragraphs.map((paragraph, index) => (
                  <p key={`${section.heading}-${index}`}>{paragraph}</p>
                ))}
              </div>
            </article>
          ))}
        </div>

        <section className="mt-10 grid gap-6 lg:grid-cols-3">
          <article className="rounded-[1.8rem] border border-white/10 bg-white/[0.04] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Bibliography Guidance
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/64">
              {bibliographyGuidance.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>

          <article className="rounded-[1.8rem] border border-white/10 bg-white/[0.04] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Suggested Charts and Tables
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/64">
              {suggestedFigures.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>

          <article className="rounded-[1.8rem] border border-white/10 bg-[linear-gradient(135deg,rgba(255,184,77,0.1),rgba(255,255,255,0.03))] p-6 lg:col-span-1">
            <p className="text-[10px] uppercase tracking-[0.34em] text-[var(--accent-soft)]">
              Evidence Still Needed
            </p>
            <div className="mt-5 space-y-4 text-sm leading-7 text-white/70">
              {evidenceNeeds.map((item) => (
                <p key={item}>{item}</p>
              ))}
            </div>
          </article>
        </section>

        <div className="mt-12">
          <Link
            href="/trade-war-shock"
            className="inline-flex min-h-[56px] items-center justify-center rounded-[999px] border border-[var(--line-strong)] px-6 text-[11px] font-extrabold uppercase tracking-[0.26em] text-white transition hover:border-[var(--accent)] hover:bg-[var(--accent)] hover:text-[var(--bg)]"
          >
            Back to Case File
          </Link>
        </div>
      </section>
    </main>
  );
}
